Galaxy workflow for SISTR v1.1.1 supporting batch processing from raw reads to reports
phac-nml/sistr_cmd pull request #47
Opened 2021-03-20 00:39 UTC by kbessonov1984

The Galaxy workflow is a nice practical addition to SISTR v1.1.1 allowing to automate processing of sequenced samples. It uses `shovill` assembler to assemble draft genomes, followed by SISTR v1.1.1 serotyping and report aggregation using `tp_cat` tool. The sample ids are preserved and are reported in `genome` field of the final sample report.

2021-03-22 16:01 UTC, apetkau requested changes
This looks great to me, thanks @kbessonov1984 .

I'm wondering if you could add a small section in the README file on the Galaxy workflow. This could include a link to this workflow file and list the tools you need to install (shovill and SISTR). You could also link to the EU Galaxy instance (where the necessary tools are installed I believe?)

2021-03-29 22:09 UTC, kbessonov1984 commented
Added changes to readme. please check section `Galaxy workflows`

2021-03-30 15:39 UTC, apetkau approved these changes

2021-03-30 15:39 UTC, apetkau commented
Looks great to me. Thanks so much @kbessonov1984

2021-03-30 15:39 UTC, merged